# Copyright (C) 2021 György Barabás
# This program comes with ABSOLUTELY NO WARRANTY. This is free software, and
# you are welcome to redistribute it under certain conditions. for details,
# see the GNU General Public License Agreement (in the file COPYING.txt).


require(tidyverse) # manipulating and visualizing data
require(ggpmisc) # adding statistics to plots
require(scales)


# show densities across the landscape through time; works for data with
# a single model and parameterization
# Input
# - dat: a data frame like the one generated by ecoevo_main.R
# Output
# - a ggplot2 figure
plot_timeseries <- function(dat) {
  # define color gradient from cold to warm colors:
  color_pal <- colorRampPalette(c("#56B4E9", "#009E73", "#E69F00"))
  S <- filter(dat, tl=="R") %>% pull(species) %>% max() # no. of resource spp.
  time.labs <- function(x) format(dat$time, scientific = TRUE)
  dat %>%
    # calculate mean densities at each time and patch for each species:
    group_by(time, species, patch, tl) %>%
    summarise(avg_n=mean(n), .groups="drop") %>%
    mutate(species=ifelse(tl=="C", species-S, species)) %>%
    mutate(species=as.factor(species),
           tl=ifelse(tl=="R", "resource species", "consumer species")) %>%
    ggplot() + # create plot
    aes(x=90/19*(patch-1), ymin=0, y=avg_n ,ymax=avg_n, colour=species, fill=species) +
    geom_ribbon(alpha=0.3) +
    # panel rows: trophic level; panel columns: time
    facet_grid(tl~time, labeller=label_bquote(col=t==.(format(time,scientific=TRUE)))) +
    coord_flip() +
    scale_x_reverse(name="latitude", expand=c(0.02, 0.02),breaks = seq(0, 90, by = 30)) +
    theme(title=element_text(size = 20), axis.text.x= element_text(size = 20),axis.text.y= element_text(size = 20),axis.title = element_text(size=22),strip.text = element_text(
      size = 22),strip.text.y = element_blank())+
    scale_y_continuous(name="population density", labels=abbreviate) +
    scale_colour_manual(values=color_pal(S)) +
    scale_fill_manual(values=color_pal(S)) %>%
  #+theme_bw() 
  #+theme(legend.position="none")
    return()
}


# show densities along continuous time at discrete locations; 
# Input
# - dat: a data frame like the one generated by ecoevo_main.R
# Output
# - a ggplot2 figure
plot_landscape <- function(dat) {
  # define color gradient from cold to warm colors:
  color_pal <- colorRampPalette(c("#56B4E9", "#009E73", "#E69F00"))
  S <- filter(dat, tl=="R") %>% pull(species) %>% max() # no. of resource spp.
      # calculate mean densities at each patch and time for each species:

  dat  %>% mutate(patch=case_when(
    (patch<=round(max(patch)/3))   ~ "Pole",
    (patch>=round(2*max(patch)/3)) ~ "Equator", 
    TRUE                           ~ "Mid")) %>%
    group_by(time, species, patch, tl) %>%
    summarise(avg_n=mean(n), .groups="drop") %>%
    mutate(species=ifelse(tl=="C", species-S, species)) %>%
    mutate(species=as.factor(species),
           tl=ifelse(tl=="R", "resource species", "consumer species")) %>%
    ggplot() + # create plot
    aes(x=avg_n , xmin=0,xmax=avg_n,y=time, colour=species, fill=species) +
    geom_ribbon(alpha=0.3) +
    # panel rows: trophic level; panel columns: patch
    facet_grid(tl~patch, labeller=label_bquote(col=.(patch))) +
    coord_flip() +
    scale_x_continuous(name="density", expand=c(0.02, 0.02)) +
    theme(title=element_text(size = 20), axis.text.x= element_text(size = 20),axis.text.y= element_text(size = 20),axis.title = element_text(size=22),strip.text = element_text(
      size = 22),strip.text.y = element_blank())+
    scale_y_continuous(name="time (years)", labels = function(x) format(x, scientific = TRUE)) +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5))+
    scale_colour_manual(values=color_pal(S)) +
    scale_fill_manual(values=color_pal(S)) %>%
    #+theme_bw() 
    #+theme(legend.position="none")
    return()
}

# show community average trait lag against community average trait dispersion
# (NOTE: there will be as many points displayed as the number of different
# community runs the input data frame "dat" contains - oncatenate results from
# multiple model runs to display each as a point)
# Input
# - dat: a data frame like the one generated by ecoevo_main.R
# Output
# - a ggplot2 figure
plot_traitlag <- function(dat) {
  smoothstp <- function(n) { # smoothed step function (vectorized)
    return(ifelse(n<1, (1*(n>0))*(n*n*n*(10+n*(-15+6*n))), 1))
  }
  Tmp <- function(x, t, tE, Cmax, Cmin, Tmax, Tmin) { # local temperatures
    return((Tmax-Tmin)*x+Tmin + ((Cmin-Cmax)*x+Cmax)*smoothstp(t/tE))
  }
  dat %>%
    # filter for only resource species:
    filter(tl=="R") %>%
    # filter for times between start & end of climate change (0 <= t <= 300):
    filter(time>=0, time<=300) %>%
    # densities below 0 (due to numerical error) are set to 0:
    mutate(n=ifelse(n<=0, 0, n)) %>%
    # calculate temperatures at each patch and each point in time:
    mutate(temp=Tmp(seq(from=0, to=1, l=50)[patch], time,
                    300, 9.66, 1.26, 25, -10)) %>%
    # compute relative densities p and weighted trait means mbar in each patch:
    group_by(time, patch, replicate, model, parameterization) %>%
    mutate(p=n/sum(n), mbar=sum(p*m)) %>%
    # create nested data, with new column (data) for local community state:
    group_by(time, patch, replicate, model, parameterization, temp, mbar) %>%
    nest() %>%
    ungroup() %>%
    # obtain trait lag and trait dispersion for each patch and time point:
    mutate(traitlag=map2_dbl(temp, mbar, `-`),
           dispersion=map2_dbl(data, mbar, ~sum(.x$p*(.x$m-.y)^2)),
           richness=map_int(data, nrow)) %>% # and also local species richness
    # finally, average all these quantities over patches and time:
    group_by(replicate, model, parameterization) %>%
    summarise(traitlag=mean(traitlag), dispersion=mean(dispersion),
              richness=mean(richness), .groups="drop") %>%
    # plot results:
    ggplot() +
    aes(x=dispersion, y=traitlag, colour=parameterization) +
    geom_point(alpha=0.2) +
    scale_colour_manual(values=c("#0072B2","#999999","#E69F00","#CC79A7")) +
    stat_fit_glance(method="lm", label.x="right", label.y="top",
                    method.args=list(formula=y~x),
                    mapping=aes(label=sprintf('R^2~"="~%.3f', stat(r.squared))),
                    parse=TRUE) +
    stat_smooth(geom="line", method=lm, se=FALSE, size=1, formula=y~x) +
    facet_wrap(~model, scales="free") +
    theme_bw() %>%
    return()
}
