# Copyright (C) 2021 György Barabás
# This program comes with ABSOLUTELY NO WARRANTY. This is free software, and
# you are welcome to redistribute it under certain conditions. for details,
# see the GNU General Public License Agreement (in the file COPYING.txt).


require(tidyverse) # manipulating and visualizing data
require(ggpmisc) # adding statistics to plots

# show densities across the landscape through time; works for data with
# a single model and parameterization
# Input
# - dat: a data frame like the one generated by ecoevo_main.R
# Output
# - a ggplot2 figure
plot_timeseries <- function(dat,nmin) {
  # define color gradient from cold to warm colors:
  color_pal <- colorRampPalette(c("#56B4E9", "#009E73", "#E69F00"))
  S <- filter(dat, tl=="R") %>% pull(species) %>% max() # no. of resource spp.
  dat %>%
    # calculate mean densities at each time and patch for each species:
    group_by(time, species, patch, tl) %>%
    summarise(avg_n=mean(n), .groups="drop") %>%
    mutate(species=ifelse(tl=="C", species-S, species)) %>%
    mutate(species=as.factor(species),
           tl=ifelse(tl=="R", "resource species", "consumer species")) %>%
    ggplot() + # create plot
    aes(x=patch, ymin=0, y=avg_n ,ymax=avg_n, colour=species, fill=species) +
    geom_ribbon(alpha=0.3) +
    # panel rows: trophic level; panel columns: time
    facet_grid(tl~time, labeller=label_bquote(row=.(tl), col=t==.(time))) +
    coord_flip() +
    scale_x_reverse(name="habitat patch number", expand=c(0.02, 0.02)) +
    scale_y_continuous(name="density", labels=abbreviate) +
    scale_colour_manual(values=color_pal(S)) +
    scale_fill_manual(values=color_pal(S)) %>%
  #+theme_bw() 
  #+theme(legend.position="none")
    return()
}


# show densities along continuous time at discrete locations; 
# Input
# - dat: a data frame like the one generated by ecoevo_main.R
# Output
# - a ggplot2 figure
plot_landscape <- function(dat) {
  # define color gradient from cold to warm colors:
  color_pal <- colorRampPalette(c("#56B4E9", "#009E73", "#E69F00"))
  S <- filter(dat, tl=="R") %>% pull(species) %>% max() # no. of resource spp.
      # calculate mean densities at each patch and time for each species:

  dat  %>% mutate(patch=case_when(
    (patch<=round(max(patch)/3))   ~ "Pole",
    (patch>=round(2*max(patch)/3)) ~ "Equator", 
    TRUE                           ~ "Mid")) %>%
    group_by(time, species, patch, tl) %>%
    summarise(avg_n=mean(n), .groups="drop") %>%
    mutate(species=ifelse(tl=="C", species-S, species)) %>%
    mutate(species=as.factor(species),
           tl=ifelse(tl=="R", "resource species", "consumer species")) %>%
    ggplot() + # create plot
    aes(x=avg_n , xmin=0,xmax=avg_n,y=time, colour=species, fill=species) +
    geom_ribbon(alpha=0.3) +
    # panel rows: trophic level; panel columns: patch
    facet_grid(tl~patch, labeller=label_bquote(col=.(patch))) +
    coord_flip() +
    scale_x_continuous(name="density", expand=c(0.02, 0.02)) +
    scale_y_continuous(name="time (years)", labels=abbreviate) +
    scale_colour_manual(values=color_pal(S)) +
    scale_fill_manual(values=color_pal(S)) %>%
    #+theme_bw() 
    #+theme(legend.position="none")
    return()
}


plot_traitLag <- function(dat,nmin) {
  # define color gradient from cold to warm colors:
  color_pal <- colorRampPalette(c("#56B4E9", "#009E73", "#E69F00"))
  S <- filter(dat, tl=="R") %>% pull(species) %>% max() # no. of resource spp.
  dat %>%filter(n> nmin)%>%
    # calculate mean densities at each time and patch for each species:
    group_by(time, species, patch, tl) %>%
    summarise(avg_n=m-Tenv, .groups="drop") %>%
    mutate(species=ifelse(tl=="C", species-S, species)) %>%
    mutate(species=as.factor(species),
           tl=ifelse(tl=="R", "resource species", "consumer species")) %>%
    ggplot() + # create plot
    aes(x=patch, ymin=0, y=avg_n ,ymax=avg_n, colour=species, fill=species) +
    geom_ribbon(alpha=0.3) +
    # panel rows: trophic level; panel columns: time
    facet_grid(tl~time, labeller=label_bquote(row=.(tl), col=t==.(time))) +
    coord_flip() +
    scale_x_reverse(name="habitat patch number", expand=c(0.02, 0.02)) +
    scale_y_continuous(name="trait lag (°C)", labels=abbreviate) +
    scale_colour_manual(values=color_pal(S)) +
    scale_fill_manual(values=color_pal(S)) %>%
    #+theme_bw() 
    #+theme(legend.position="none")
    return()
}
